version: '3.3'

services:
  dynamodb:
    container_name: dynamodb-local
    image: amazon/dynamodb-local
    restart: always
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    ports:
      - "8000:8000"

  main:
    container_name: main
    build: .
    env_file:
      - .env

volumes:
  dynamodb_data: