version: '3'

services:
  dynamodb:
    container_name: dynamodb-local
    image: amazon/dynamodb-local:latest
    restart: always
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data
    ports:
      - "8000:8000"

volumes:
  dynamodb_data: